version: "3.8"

services:
  api:
    container_name: api
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./back/ComposeDockerfile
      target: development
    ports:
      - "9090:9090"
    expose:
      - "9090"
    restart: always
    env_file:
      - ./back/.env
    networks:
      - backend

  db:
    container_name: mysql_db
    image: mysql:latest
    volumes:
      - db_data_info:/mysql
    restart: always
    env_file:
      - ./back/.db.env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - backend

  web:
    container_name: web
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./front/ComposeDockerfile
      target: development
    ports:
      - "4200:4200"
    expose:
      - "4200"
    restart: always
    networks:
      - backend

volumes:
  db_data_info: {}
networks:
  backend:
    driver: bridge
