version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./back/ComposeDockerfile
      target: development
    ports:
      - "9090:9090"
    expose:
      - "9090"
    restart: always
    environment:
      NODE_ENV: "produc"
    env_file:
      - ./back/.env
    networks:
      - backend

  web:
    container_name: web
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./front/ComposeDockerfile
    ports:
      - "80:80"
    expose:
      - 80
    restart: always
    environment:
      NODE_ENV: "produc"
    networks:
      - backend

volumes:
  db_data_info: {}
networks:
  backend:
    driver: bridge
